myCourse = '####'         #Canvas Course Number
emailPassword = '####'    #Create an app-specific password for your school issued Gmail Account
emailAddress = '####'     #Your School specific e-mail account
courseName = 'Pre-Calculus w/ Advanced Topics'  #What you'd like your course to be called in reports
standardType1 = 'MP.'     #Text that will only be in the first type of standard (Typically Process standards)
standardType2 = '.A.'     #Text that will only be in the second type of standard (Typically content standards)
standardType3 = '.C.'     #Text that will only be in the third type of standard (Typically content standards)
TOKEN = '####'            #Create a token in Canvas to give script access to your grades
PAGES = '2000'            #Keep a large number so script can pull in many scores at once
